从 1w 刀亏到现在只剩 200 刀，那么要怎么办呢？

* DONE BCH Entry:1498 Target:1600 StopLose:Nan LiqPrice:934.25 Load:Half Total:211$
  CLOSED: [2017-12-05 Tue 17:44] SCHEDULED: <2017-12-04 Mon>

  2016-12-05
  quit:1525   profits:4$
  不应该中途退出，很快应该价格达到 1600，只吃到很少一部分利润。
  如果觉得有更好的机会，可以减仓，但不能完全清仓。

  2016-12-06
  时机上并没有打到 1600，价格 6 号回到了 1415，时机上当时退出是个非常正确的决定.
  
* DONE IOTA Entry:2.613 Target:3.19  StopLose:Nan LiqPrice:1.39 Load:Half Total:215$
  CLOSED: [2017-12-05 Tue 17:44] SCHEDULED: <2017-12-04 Mon>


  2016-12-05
  Target:3.19 完美。。。这次盈利 85$.

  2016-12-06
  IOTA 价格又突破了 3.8，当时 3.19 收摊时曾考虑低点再入手，可惜没买，现在只能再等下次机会了。

* DONE EOS Entry:3.8 Target:4.82  StopLose:Nan LiqPrice:2.06 Load:Half Total:301$
  CLOSED: [2017-12-06 Wed 17:56] SCHEDULED: <2017-12-05 Tue>
  
  EOS 可以 VS ETH，非常有前途，也许可以长期做多，先从 3.8 开始做一次，估计 12-09 08:00 达到 target.
  4.6 退出，盈利 125 刀，还是不错，但是 EOS 很快涨到了 5.2，还是过早退出了。可以继续使用 tail top，等其下降时再退出。

* DONE ETC Entry:27.061 Target:32  StopLose:Nan LiqPrice:14.686 Load:Half Total:413$
  CLOSED: [2017-12-06 Wed 21:18] SCHEDULED: <2017-12-05 Tue>
  
  Etc 刚好到支持线，是买入时机，准备承受这个风险，半仓买入了 ETC。

  FAIL. 失败，ETC 跌破了支撑线，获取到教训。

  不要在支撑点买入！！！！！！！！应在支撑点出现明显回弹再买入。
  
 

* DONE EOS Entry:4.83 Target:5.82  StopLose:Nan LiqPrice:2.56 Load:Half Total:391$
  CLOSED: [2017-12-07 Thu 21:40] SCHEDULED: <2017-12-05 Tue>
  
  EOS 可以继续做多。

* DONE IOTA Entry:3.71 Target:6.2  StopLose:Nan LiqPrice:2.24 Load:Half Total:382$
  CLOSED: [2017-12-08 Fri 09:46] SCHEDULED: <2017-12-07 Thu>
  
  btc 今天一路疯长，突破了 15000，其他所有币种均下降，所以是其他币种的很好的买入时机。

  每次 BTC 突破新高，其他所有币种呈下降趋势，等 btc 涨过之后，会引来其他币种的集体恢复，这时候挑选有潜力的上车。

  由于 IOTA 和 EOS 最近涨的很猛，我挑选了 IOTA 上车。

  * 早上起来 IOTA 涨到 4.2，涨幅超过 20%，我没有卖，觉得还会涨。不到一会跌倒了 3.88，我卖了。。
  * 合理止盈，不要贪。




* DONE BCH Entry:1424 Target:1524  StopLose:Nan LiqPrice:891 Load:Half Total:572$
  CLOSED: [2017-12-10 Sun 09:32]

  这几做短线又盈利了 200 刀，重新上车 bch。

  本来昨天晚上感到 ltc 会暴涨，110 上了车，但是使用 trail stop 止损把自己震荡下车了，错过了一次机会。
  果然，刚开始入场不用使用 trail stop，很容易提前被震出局，必须要用盈利之后使用。可以锁定利润。
  
  1. 这个时候以 1424 的价格买入 bch 价格有点高。1400 应该也可以买入。
  2. 1 单应该做长久一点，不能频繁上下车。

* DONE Total:507$

  昨天开始想换车上，查看 bitfix 上的买卖深度，换了几个币种，亏了 60 多刀，感觉每一个币种的卖压都很重，实在不知道买什么好。睡觉前清仓。

  第 2 天起床，所有的币种都成下跌之势，所以：

  1. 当所有币种都存在极大的卖压时。
  2. stoch rsi 大于 70 左右，很有可能会由高走低。
  3. 非常适合下空单。


* TODO BTC Entry:13510 target:NAN StopLose:Nan LiqPrice:10274  Load:2/3 Total: 457$

  1) 基本上所有币种都在下跌，但是 btc 率先走完了 stoch rsi 4 小时的低谷，并且观察买压很重，价格应该会至少反弹一拨。所以做空。
  2) 同一时间其他币种还没有走完 stoch rsi 4 小的下跌.

     




